services:
  - type: web
    name: open-saas
    env: node
    buildCommand: npm install -g wasp && wasp build
    startCommand: wasp start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: open-saas-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://open-saas.onrender.com
      - key: REACT_APP_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: ADMIN_EMAILS
        sync: false

databases:
  - name: open-saas-db
    databaseName: open_saas
    user: open_saas
    plan: free 